api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        stateless: false #TODO set to true as soon as we removed session
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
